baseURL = "https://karibunyumanibytj-web.github.io/Solar-Guide-Kenya/"
languageCode = "en-us"
title = "Solar Guide Kenya"
theme = "PaperMod"

# This line blocks the invisible files that are causing the "art-x-" crash
ignoreFiles = ["\\.DS_Store", "._.*", "\\.gitkeep"]

[params]
    env = "production"
    defaultTheme = "auto"

[params.homeInfoParams]
    Title = "Welcome to Solar Guide Kenya ☀️"
    Content = "The best guide for solar in Kenya."

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Reviews"
    url = "posts/"
    weight = 20
