baseURL = "https://karibunyumanibytj-web.github.io/Solar-Guide-Kenya/"
languageCode = "en-us"
title = "Solar Guide Kenya"
theme = "PaperMod"

[params]
    env = "production"
    defaultTheme = "auto"

[params.homeInfoParams]
    Title = "Welcome to Solar Guide Kenya ☀️"
    Content = "The best guide for solar energy solutions in Kenya."

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Solar Reviews"
    url = "/posts/"
    weight = 20

[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 30

[[menu.main]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 40
