baseURL = "https://karibunyumanibytj-web.github.io/Solar-Guide-Kenya/"
languageCode = "en-us"
title = "Solar Guide Kenya"
theme = "PaperMod"

[params]
    env = "production"
    defaultTheme = "auto"
    # ADD THESE THREE LINES:
    ShowToc = true
    TocOpen = false
    ShowReadingTime = true
    
   [params.homeInfoParams]
    Title = "Solar Guide Kenya ☀️"
    Content = "Cutting through the noise to find you the best solar deals in Nairobi."

[[params.homeInfoParams.buttons]]
    name = "View 2026 Price Guide"
    url = "posts/top-5-hybrid-inverters" # Make sure this matches your post link
[[params.homeInfoParams.buttons]]
    name = "Get a Quote"
    url = "contact"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Solar Reviews"
    url = "/posts/"
    weight = 20

[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 30

[[menu.main]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 40
